### PR TITLE
Rewind the request body

### PR DESCRIPTION
**Pull request by cobbr2**
Allows for simpler integration of services that already receive SNS.

### CODE REVIEW

**Comment by cobbr2** [comment]
Hmm.  After poking around, I've narrowed down the problem with the 1.9.3 build to the combination of the version of `rubygems` and the version of  `bundler`:

| gem --version | bundler --version | result |
+---+----+---+
| 2.5.1 | 1.7.6 | **fail** as we see on travis |
| 2.4.2 | 1.7.6 | bundles fine, passes tests |
| 2.5.1 | 1.11.2 | bundles fine, passes tests |

Would it be possible to modify the travis.yml to move to one of the combinations that work?

**Comment by cobbr2** [comment]
Transcript at https://gist.github.com/cobbr2/b1511a530612ebf1fd6c

**Comment by benzado** [comment]
Thanks to the head start you gave me, I was able to update `travis.yml` to fix the problem and also add 2.1 and 2.2 to the target platforms.

I think if I merge PR #10 into master it will create a conflict with this branch (I also edited the Gemfile). Since you'll have to fix it up anyway, why don't you merge those changes into this branch? (You could also squash those commits while you're at it; I made all the edits via GitHub's web UI. Trippy!)

**Comment by cobbr2** [comment]
Fantastic. I'll put something together, but probably not for a few hours. And I'm a bit upset with myself for not finding the `.travis.yml` file in the first place; **argh**. Thanks!

**Comment by cobbr2** [comment]
This looks like it's ready to go.  And thanks for the rebase practice.

**Pull request merged**
