### PR TITLE
Relax rack requirement

### LINKED ISSUE #11: Relax version requirement for rack
I'm trying to use this with rails 5, and it's not working because rails5 depends on rack 2.x. If you could relax the requirement to `>= 1.4`, that would solve this problem.

### PR DESCRIPTION
**Pull request by fschwahn**
Fixes #11

### CODE REVIEW

**Comment by benzado** [comment]
Well, we've learned something. Apparently Rack 2.0.1 requires Ruby 2.2.2 or later, and Bundler can't take that into account when installing gems.

**Comment by fschwahn** [comment]
Always be learning 😃  

We need to use a build matrix to test against rack 1.x and 2.x separately, like here: https://github.com/plataformatec/devise/blob/master/.travis.yml

**Comment by fschwahn** [comment]
I've added separate tests for rack 1.x & 2.x, travis passes now.

**Comment by benzado** [comment]
Hey, thanks for taking care of that. I'll see about getting this published to rubygems right now.

**Pull request merged**
